apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-issuer-ho
spec:
  acme:
    email: user@example.com
    server: http://10.0.8.207:8200/v1/pki_int/acme/directory 
    privateKeySecretRef:
      name: example-issuer-account-key-ho
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx